name: complex
on: push
jobs: 
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run : date
  windows:
    runs-on: windows-latest
    steps:
      - run : date
  macos:
    needs: [ubuntu]
    runs-on: macos-latest
    steps:
      - run : date
  depends:
    needs: [ubuntu, windows, macos]
    runs-on: macos-latest
    steps:
      - run : date
